### ISSUE TITLE
CUDA installation error

### ISSUE THREAD

**Issue by ngoquanghuy99** [markjay4k/Install-Tensorflow-on-Ubuntu-17.10-#3]
When i ran this command: sudo apt-get install cuda, i got this error: 
![image](https://user-images.githubusercontent.com/36761076/44491064-44840300-a68a-11e8-9f08-ff47bbc3aaac.png)
Somebody please give me a solution to solve this. Thanks!

**Comment by MaraniMatias** [comment]
sudo apt-get install aptitude
sudo aptitude install cuda

**Comment by maky-hnou** [comment]
> sudo apt-get install aptitude
> sudo aptitude install cuda

That solved my problem, thank you!

**Comment by WrathofBhuvan11** [comment]
not 

> sudo apt-get install aptitude
> sudo aptitude install cuda

not working bro

**Comment by MaraniMatias** [comment]
Try this https://github.com/MaraniMatias/Install-Tensorflow-GPU-on-Ubuntu-18.04-gtx-1070ti

**Comment by WrathofBhuvan11** [comment]
> Try this https://github.com/MaraniMatias/Install-Tensorflow-GPU-on-Ubuntu-18.04-gtx-1070ti
ThankYou for your reply...!
But why should we download cuda 10.0 if we already have installed 9.0? And also TF-GPU won't support 10.0 yet, only 9.0 does,..
please check this link https://medium.com/@taylordenouden/installing-tensorflow-gpu-on-ubuntu-18-04-89a142325138

**Comment by MaraniMatias** [comment]
> > Try this https://github.com/MaraniMatias/Install-Tensorflow-GPU-on-Ubuntu-18.04-gtx-1070ti
> > ThankYou for your reply...!
> > But why should we download cuda 10.0 if we already have installed 9.0? And also TF-GPU won't support 10.0 yet, only 9.0 does,..
> > please check this link https://medium.com/@taylordenouden/installing-tensorflow-gpu-on-ubuntu-18-04-89a142325138

Probably i have install cuda 9 and cuda 10, i not can check this, now.
This guia https://www.tensorflow.org/install/gpu#linux_setup is similar to my repo on github.

You can install cuda 9.x the guia is equal

**Comment by WrathofBhuvan11** [comment]
> > > Try this https://github.com/MaraniMatias/Install-Tensorflow-GPU-on-Ubuntu-18.04-gtx-1070ti
> > > ThankYou for your reply...!
> > > But why should we download cuda 10.0 if we already have installed 9.0? And also TF-GPU won't support 10.0 yet, only 9.0 does,..
> > > please check this link https://medium.com/@taylordenouden/installing-tensorflow-gpu-on-ubuntu-18-04-89a142325138
> 
> Probably i have install cuda 9 and cuda 10, i not can check this, now.
> This guia https://www.tensorflow.org/install/gpu#linux_setup is similar to my repo on github.
> 
> You can install cuda 9.x the guia is equal

hmm.. finished installing... but i'm getting same problem prior to this reinstall. Actually yesterday i ran a program and it showed this error,. So I decided to reinstall the TF-GPU .... Now i'm getting same error again... Previously many time i used my GPU but this time it;s showing this error
![yr](https://user-images.githubusercontent.com/36232037/50010205-cb187380-ffde-11e8-9fa1-139b92b1378c.png)
I have attached the screenshot of the terminal. Please take a look ...

**Comment by MaraniMatias** [comment]
I using python 3.6 or hither, Will it be the problem?

**Comment by ngoquanghuy99** [comment]
Done!
